# Generated by Django 5.1.4 on 2024-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField(auto_now_add=True)),
                ('HORA', models.TimeField(auto_now_add=True)),
                ('MAQUINA_DE_FREON', models.CharField(choices=[('ICESTA 1', 'ICESTA 1'), ('ICESTA 2', 'ICESTA 2'), ('ICESTA 3', 'ICESTA 3'), ('ICESTA 4', 'ICESTA 4'), ('ICESTA 5', 'ICESTA 5'), ('ICESTA 6', 'ICESTA 6'), ('ICESTA 7', 'ICESTA 7'), ('ICESTA 8', 'ICESTA 8'), ('ICESTA 9', 'ICESTA 9'), ('ICESTA 10', 'ICESTA 10'), ('ICESTA 11', 'ICESTA 11'), ('ICESTA 12', 'ICESTA 12'), ('ICESTA 13', 'ICESTA 13'), ('ICESTA 14', 'ICESTA 14'), ('ICESTA 15', 'ICESTA 15'), ('ICESTA 16', 'ICESTA 16'), ('ICESTA 17', 'ICESTA 17'), ('ICESTA 18', 'ICESTA 18'), ('ICESTA 19', 'ICESTA 19'), ('ICESTA 20', 'ICESTA 20'), ('HOWE 1', 'HOWE 1'), ('HOWE 2', 'HOWE 2'), ('HOWE 3', 'HOWE 3'), ('GENEGLACE 1', 'GENEGLACE 1'), ('GENEGLACE 2', 'GENEGLACE 2'), ('GENEGLACE 3', 'GENEGLACE 3'), ('GENEGLACE 4', 'GENEGLACE 4'), ('CHILLER', 'CHILLER')], default='ICESTA 1', max_length=20)),
                ('HORARIO', models.CharField(choices=[('8:00', '8:00'), ('18:00', '18:00'), ('22:00', '22:00')], default='8:00', max_length=20)),
                ('TEMPERATURA_DE_AGUA_DE_INGRESO', models.PositiveIntegerField()),
                ('TEMPERATURA_DE_AGUA_DE_TINA', models.PositiveIntegerField()),
                ('SALINIDAD_DE_AGUA_EN_TINA', models.PositiveIntegerField()),
                ('PRESION_BAJA_PSIG', models.PositiveIntegerField()),
                ('CORRIENTE', models.PositiveIntegerField()),
                ('VOLTAJE', models.PositiveIntegerField()),
                ('CONTOMETRO_1', models.PositiveIntegerField(blank=True, null=True)),
                ('CONTOMETRO_2', models.PositiveIntegerField(blank=True, null=True)),
                ('MOTIVO_DE_PARADA', models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('SILO LLENO', 'SILO LLENO'), ('VOLTAJE ALTO', 'VOLTAJE ALTO'), ('FALLA ELÉCTRICA', 'FALLA ELÉCTRICA'), ('FALLA MECÁNICA', 'FALLA MECÁNICA'), ('FALLA REFRIGERACION', 'FALLA REFRIGERACION'), ('MTTO. PLANIFICADO', 'MTTO. PLANIFICADO'), ('CORTE DE ENERGÍA', 'CORTE DE ENERGÍA'), ('REPARACIÓN DE BAZUCA', 'REPARACIÓN DE BAZUCA')], default='NINGUNO', max_length=25)),
                ('HORAS_DE_PARADA', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField(auto_now_add=True)),
                ('HORA', models.TimeField(auto_now_add=True)),
                ('RACKS', models.CharField(choices=[('ICESTA 1', 'ICESTA 1'), ('ICESTA 2', 'ICESTA 2'), ('ICESTA 3', 'ICESTA 3'), ('ICESTA 4', 'ICESTA 4'), ('ICESTA 5', 'ICESTA 5'), ('ICESTA 6', 'ICESTA 6'), ('RACK 7', 'RACK 7'), ('ICESTA 8', 'ICESTA 8'), ('ICESTA 9', 'ICESTA 9'), ('RACK 10-11', 'RACK 10-11'), ('RACK 12-13', 'RACK 12-13'), ('ICESTA 14', 'ICESTA 14'), ('RACK 15-16', 'RACK 15-16'), ('ICESTA 17', 'ICESTA 17'), ('ICESTA 18', 'ICESTA 18'), ('ICESTA 19', 'ICESTA 19'), ('ICESTA 20', 'ICESTA 20'), ('SISTEMA NH3', 'SISTEMA NH3')], default='ICESTA 1', max_length=100)),
                ('ESTADO_DEL_CONDENSADOR', models.CharField(choices=[('Muy Sucio', 'Muy Sucio'), ('Sucio', 'Sucio'), ('Limpio', 'Limpio')], default='Sucio', max_length=20)),
                ('NIVEL_DE_REFRIGERANTE', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Medio', max_length=20)),
                ('PRESION_ALTA_PSIG', models.PositiveIntegerField()),
                ('PRESION_DE_BAJA_COMP_1', models.PositiveIntegerField(blank=True, null=True)),
                ('PRESION_DE_BAJA_COMP_2', models.PositiveIntegerField(blank=True, null=True)),
                ('CORRIENTE', models.PositiveIntegerField(blank=True, null=True)),
                ('VOLTAJE', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
