# Generated by Django 5.1.4 on 2024-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registroracks',
            constraint=models.UniqueConstraint(fields=('RACKS', 'FECHA'), name='unique_rack_per_day'),
        ),
    ]
