# Generated by Django 5.1.4 on 2024-12-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registroracks_unique_rack_per_day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registromaquinas',
            constraint=models.UniqueConstraint(fields=('MAQUINA_DE_FREON', 'FECHA', 'HORARIO'), name='unique_MAQUINA_DE_FREON_per_day'),
        ),
    ]
