# Generated by Django 5.1.4 on 2024-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registromaquinas_unique_maquina_de_freon_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField()),
                ('MAQUINA', models.CharField(max_length=100)),
                ('HORARIO', models.TimeField()),
                ('CONTOMETRO', models.IntegerField()),
            ],
            options={
                'ordering': ['FECHA', 'HORARIO'],
            },
        ),
    ]
