# Generated by Django 5.1.4 on 2024-12-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_registrocontometro_contometro2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocontometro',
            name='CONTOMETRO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocontometro',
            name='CONTOMETRO2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
